name: Test Backend

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: pedido_facil_user
          POSTGRES_PASSWORD: pedido_facil_pass
          POSTGRES_DB: pedido_facil_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U pedido_facil_user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Rodar testes com pytest
        env:
          DATABASE_URL: postgresql://pedido_facil_user:pedido_facil_pass@localhost:5432/pedido_facil_db
        run: |
          source venv/bin/activate
          pytest backend/tests --disable-warnings --cov=backend/app --cov-report=xml

      - name: Upload de cobertura de testes
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: true
